name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  asuka: ^2.0.0
  flutter_bloc: ^8.0.0
  http: ^0.13.4
  flutter_modular: ^4.4.0+1
  json_annotation: ^4.0.1
  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/